### ISSUE TITLE
Docx file type

### ISSUE THREAD

**Issue by ArYaNsH** [whiteoctober/silex-technical-test#2]
Hi, I've been trying to upload docx files but in vain, asserting 'mimeTypes' => array("application/msword") only allows doc files

**Comment by sampart** [comment]
Hi @ArYaNsH,

This list of mime types should be what you need: http://stackoverflow.com/a/4212908/328817

Thanks
Sam

**Comment by ArYaNsH** [comment]
Thank you so much, I got it working.
